/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "OAuth.h"

bool_t
xdr_req_auth_req (XDR *xdrs, req_auth_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->cliend_id, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_auth_resp (XDR *xdrs, req_auth_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error_message, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_req_token_req (XDR *xdrs, approve_req_token_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_signed_token (XDR *xdrs, signed_token *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->perms))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_req_token_resp (XDR *xdrs, approve_req_token_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_signed_token (xdrs, &objp->auth_signed_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_access_token_req (XDR *xdrs, req_access_token_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->cliend_id, ~0))
		 return FALSE;
	 if (!xdr_signed_token (xdrs, &objp->auth_signed_token))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->auto_refresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_access_token_resp (XDR *xdrs, req_access_token_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valability))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error_message, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_refresh_token_req (XDR *xdrs, req_refresh_token_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_refresh_token_resp (XDR *xdrs, req_refresh_token_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->new_access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->new_refresh_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_req (XDR *xdrs, validate_delegated_action_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->operation_type, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_resp (XDR *xdrs, validate_delegated_action_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->message, ~0))
		 return FALSE;
	return TRUE;
}
