/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "OAuth.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
